import os
import sendgrid
from sendgrid.helpers.mail import Mail

def send_email():
    # Initialize SendGrid client
    sg = sendgrid.SendGridAPIClient(api_key=os.environ.get('SENDGRID_API_KEY'))
    
    # Sender and recipient emails from environment variables
    sender_email = os.environ.get('SENDGRID_SENDER_EMAIL')
    recipient_email = os.environ.get('SENDGRID_RECIPIENT_EMAIL')

    # Read the HTML output file generated by the Jupyter notebook
    try:
        with open('output.html', 'r') as f:
            html_content = f.read()
    except FileNotFoundError:
        print("Error: 'output.html' file not found. Make sure the Jupyter notebook runs successfully.")
        return  # Exit if the file is not found

    # Create email content
    message = Mail(
        from_email=sender_email,  # Use the sender email from the environment
        to_emails=recipient_email,  # Use the recipient email from the environment
        subject='Automated Jupyter Notebook Report',
        html_content=html_content
    )

    # Send the email
    try:
        response = sg.send(message)
        print(f"Email sent successfully: {response.status_code}")
    except Exception as e:
        print(f"Error sending email: {e}")

if __name__ == "__main__":
    send_email()
