name: Run Jupyter Notebook

on:
  schedule:
    - cron: '0 0 * * *' # This will run at midnight UTC every day

jobs:
  run_notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # You can specify any version you need

      - name: Install Jupyter and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert
          # pip install -r requirements.txt Optional: If you have dependencies listed

      - name: Run the Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute Hackney Tennis Auto Booking.ipynb --output output_notebook.ipynb
          
      - name: Email the output (using SendGrid)
        run: |
          pip install sendgrid
          python -c "
          import sendgrid
          from sendgrid.helpers.mail import Mail
          import os

          sg = sendgrid.SendGridAPIClient(api_key=os.environ.get('SENDGRID_API_KEY'))
          email_content = open('output_notebook.ipynb', 'r').read()
          message = Mail(
              from_email='markonisic1998@gmail.com',
              to_emails='markonisic@gmail.com',
              subject='Jupyter Notebook Output',
              plain_text_content=email_content,
              html_content=email_content)
          
          sg.send(message)
          "
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }} # Set up this secret in your repo settings
