name: Run Jupyter Notebook and Email Output

on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install nbconvert notebook pandas sendgrid selenium webdriver-manager prettytable
      shell: bash

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to html --execute hackney_tennis_auto_booking.ipynb --output output.html
      shell: bash

    - name: Check output.html content (for debugging)
      run: |
        cat output.html
      shell: bash

    - name: List files in current directory (debugging step)
      run: ls -al
      shell: bash

    - name: Send Email with SendGrid
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        SENDGRID_SENDER_EMAIL: ${{ secrets.SENDGRID_SENDER_EMAIL }}
        SENDGRID_RECIPIENT_EMAIL: ${{ secrets.SENDGRID_RECIPIENT_EMAIL }}
      run: |
        python send_email.py
