name: Run Jupyter Notebook and Email Output

# Schedule to run at 11:30 PM UTC every day and also allow manual trigger
on:
  schedule:
    - cron: '30 23 * * *'  # Runs at 11:30 PM UTC every day
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Use Python 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install from requirements.txt

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to html --execute hackney_tennis_auto_booking.ipynb --output output.html || { echo 'Jupyter Notebook execution failed'; exit 1; }
      shell: bash

    - name: Send Email with SendGrid
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        SENDGRID_SENDER_EMAIL: ${{ secrets.SENDGRID_SENDER_EMAIL }}
        SENDGRID_RECIPIENT_EMAIL: ${{ secrets.SENDGRID_RECIPIENT_EMAIL }}
      run: |
        python send_email.py || { echo 'Email sending failed'; exit 1; }
